# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Blog of Words
email: archenoth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to The Blog of Words -- The wordiest words that ever worded.
  A blog about tech, and occasionally other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://archenoth.com" # the base hostname & protocol for your site
twitter_username: Archenoth
github_username:  Archenoth

# Build settings
markdown: kramdown
